class NonZeroHighBitError extends Error {};
class InvalidPcUpdateError extends Error {};
class InvalidResError extends Error {};
class InvalidOpcodeError extends Error {};
class InvalidApUpdateError extends Error {};
class InvalidOp0RegisterError extends Error {};
class InvalidOp1RegisterError extends Error {};
class InvalidDstRegisterError extends Error {};
class AssertEqError extends Error {};
